OUTDIR: ./
NWKDIR: /home/lix32/CDSLSahinalp/yuelin/{}_10pi/t{}/tree.nwk
PARTITION_VALIDITY_THRESHOLD: .5
MINIMUM_SUBTREE_SIZE: .05

PATIENTS:
    CRC01:
        t_opt: 8
    CRC02:
        t_opt: 26
    CRC04:
        t_opt: 17
    CRC10:
        t_opt: 4
    CRC11:
        t_opt: 8
    CRC12:
        t_opt: 23
    CRC13:
        t_opt: 13
    CRC14:
        t_opt: 28
    CRC15:
        t_opt: 21