configfile: "config_4_patients.yaml"

PATIENTS=list(config['PATIENTS'].keys())
if config['OUTDIR'] == './':
    OUTDIR = ''
else:
    OUTDIR = config['OUTDIR']

NWKDIR = config['NWKDIR']
INDIR = config['INDIR']

rule all:
    input:
        expand(OUTDIR.format(patient)+"fast_js_dis.npz",  patient=PATIENTS )


def get_js_input(ws):
    return NWKDIR.format(ws.patient,config['PATIENTS'][ws.patient]['t_opt']), \
           INDIR.format(ws.patient)+"{}_cpg_met_rate_mat.npz".format(ws.patient)




rule compute_js_dis: 
    input:
        get_js_input
    output:
        OUTDIR+"{patient}/js_dis.npz"
    params:
        partition_validity_threshold = config['PARTITION_VALIDITY_THRESHOLD'],
        minimum_subtree_size = config['MINIMUM_SUBTREE_SIZE']
    threads:
        4
    log:
        OUTDIR+"{patient}/logs/compute_js_dis.log"
    conda:
        "sgootr.yml"
    shell:
        "python compute_js_dis.py {input} {output} {params.partition_validity_threshold} " \
        "{params.minimum_subtree_size} {threads} {log}"
        