configfile: "config_test.yaml"

PATIENTS=list(config['PATIENTS'].keys())
if config['OUTDIR'] == './':
    OUTDIR = ''
else:
    OUTDIR = config['OUTDIR']

NWKDIR = config['NWKDIR']
#INDIR = config['INDIR']

# rule all:
#     input:
#         expand(OUTDIR+"{patient}/all_sites_delta10_js/js_dis.npz",  patient=PATIENTS )


# def get_js_input(ws):
#     return NWKDIR.format(ws.patient,config['PATIENTS'][ws.patient]['t_opt']), \
#            INDIR.format(ws.patient)+"{}_cpg_met_rate_mat.npz".format(ws.patient)


rule all:
    input:
        expand(OUTDIR+"{patient}/js_dis.npz",  patient=PATIENTS )
# process heuristically called status matrix


def get_js_input(ws):
    print(ws.patient)
    print(PATIENTS)
    print( NWKDIR.format(ws.patient,ws.patient))
    print(OUTDIR+ws.patient+"/heuristically_called_statuses.npz")
    return NWKDIR.format(ws.patient,config['PATIENTS'][ws.patient]['t_opt']), \
           OUTDIR+ws.patient+"/heuristically_called_statuses.npz"




rule compute_js_dis: 
    input:
        get_js_input
    output:
        expand(OUTDIR+"{patient}/js_dis.npz",  patient=PATIENTS )
        #OUTDIR+"{patient}/all_sites_delta10_js/js_dis.npz"
    params:
        partition_validity_threshold = config['PARTITION_VALIDITY_THRESHOLD'],
        minimum_subtree_size = config['MINIMUM_SUBTREE_SIZE']
    threads:
        4
    log:
        OUTDIR+"{patient}/logs/compute_js_dis.log"
    conda:
        "sgootr.yml"
    shell:
        "python compute_js_dis.py {input} {output} {params.partition_validity_threshold} " \
        "{params.minimum_subtree_size} {threads} {log}"
        