RUN_TIME: 10000
p: .5
q: .75
k: 2
INDIR: /home/lix32/met_data_all_patients/key_met/all_site_delta10/{}_delta_10_frac.txt
OUTDIR: /home/lix32/met_data_all_patients/key_met/test_falafl/p{}_q{}_k{}/

PATIENT_LIST:
    ['CRC01','CRC10','CRC02','CRC12'],
    ['CRC10','CRC11','CRC04','CRC12']


PATIENTS:
    LEFT: 
        CRC01
        CRC10
        CRC11
        CRC13
    RIGHT:
        CRC02
        CRC04
        CRC15
    RECTUM:
        CRC12
        CRC14
