import random
configfile: "config.yaml"


rule all:
    input:
        expand(OUTDIR+"{patient}/js_dis.npz",  patient=PATIENTS )

def get_js_input(ws):
    return NWKDIR.format(ws.patient,config['PATIENTS'][ws.patient]['t_opt']), \
           OUTDIR+ws.patient+"/heuristically_called_statuses.npz"
 
rule process:
    input:
    output:
    params:
        p = config['p']
        k = config['k']
    threads: 
        2
    shell:

   
rule falafl:
    input:
    output:
    params:
        q = config['q']
        run_time = config['RUN_TIME']
    threads: 
        2
    shell:
        "python falafl.py" \
        "-ib " \
        "-if " \
        "-o " \
        "-q {params.q} " \
        "-c {threads}" \
        "-t {params.run_time}"
 
        